config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/about' => 'pages#about', as: :about
  get '/contact' => 'pages#contact', as: :contact
  get '/chat', to: 'rooms#show'
  root to: 'posts#index'
  resources :posts do
    collection do
      get :bookmarks
    end
    member do
      get :like
    end
    resources :comments, param: :id, only: [:create, :destroy] do
      get :approve
    end
  end
  devise_for :users
  get '/:id' => 'users#show', as: :user

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :integer          not null, primary key
#  title            :string
#  body             :text
#  slug             :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  banner_image_url :string
#  user_id          :integer
#  hidden           :boolean          default("false")
#  likes            :integer          default("0")
#
# Indexes
#
#  index_posts_on_slug  (slug) UNIQUE
#

class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  scope :most_recent, -> { order(created_at: :desc) }

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :bookmarks]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]
  before_action :require_permission, only: [:edit, :destroy, :update]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(:hidden => false).most_recent.paginate(:page => params[:page], :per_page => 6)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def bookmarks
    @posts = Post.where(:hidden => false).most_recent
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:success] = 'Post was successfully created.'
      redirect_to @post
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.update(post_params)
      flash[:success] = 'Post was successfully updated.'
      redirect_to @post
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    flash[:success] = 'Post was successfully deleted.'
    redirect_to user_path(@post.user.username)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def require_permission
      unless current_user.own?(@post)
        redirect_to root_path
      end   
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :banner_image_url, :hidden)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="row edit_post">
    <div class="col-md-4">
      <div class="card">
          <% if @post.new_record? %>
            <h4 class="card-title last">New post</h4>
          <% else %>
            <h4 class="card-title last">
              <b>Edit</b>
              <span, style='font-weight: 300;'>"<%= @post.title %>"</span>
            </h4>
          <% end %>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="field">
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control' %>
            </div>
          </li>
          <li class="list-group-item">
            <div class="field">
              <%= f.label :banner_image_url %>
              <%= f.text_field :banner_image_url, class: 'form-control'   %>
            </div>
          </li>
        </ul>
        <div class="card-block last">  
          <div class="action", style="display: inline; float: left;">
            <%= f.submit class: "btn btn-outline-primary", style: "border-radius: 0px;"%>
          </div>
          <% if @post.persisted? %>
            <%= link_to "Cancel", post_path, class: "btn btn-outline-danger", style: "float: right; border-radius: 0px;" %>
          <% else %>
            <%= link_to "Cancel", root_path, class: "btn btn-outline-danger", style: "float: right; border-radius: 0px; " %>
          <% end %>
        </div>
      </div>
      <div style="margin-top: 10px;float: right">
        <span style="margin-right: 10px;">U can hide dis post</span>
        <%= f.check_box :hidden %>
      </div>
    </div>
      <div class="col-md-8">
        <div class="field">
        <%= f.text_area :body %>
      </div>
  </div>
  <br>
<% end %>

app/views/posts/_post.html.erb
<div class = 'col-sm-6 col-lg-4'>
  <div class = 'card'>
    <div class="card-topper" style = 'background-image: url(<%= post.banner_image_url%>)'></div>
    <div class="card-block">
      <h4 class="card-title"><%= link_to post.title, post%><%= link_to " @#{post.user.username}", user_path(post.user.username), style: 'color: gray; font-weight: 300; font-size: 17px'%></h4>
      <p class="published-date"><%= post.created_at.strftime("%d %b. %Y") %></p>
      <p class="card-text", style="height: 70px;"><%=truncate(strip_tags(post.body), length:130, separator:' ') %></p>
      <div class = 'btn btn-read'><%= link_to 'Read', post %></div>
      <% if current_user %>
        <span class='hover_this btn btn-read'>
          <%= link_to "#", class:'likes_counter', remote: true do %>
            <% if Like.where(user_id: current_user).find_by(post_id: post)%>
              <span class="like_img">
            <% else %>
              <span class="not_liked like_img">
            <% end %>
              <%= image_tag('like.svg')%></span>
              <span  class='likes_val' style='color:black' data-id="<%= post.id %>"><%= Like.where(post_id: post.id).count %></span>
              <span class='who_likes hidden'>
                <% if Like.where(user_id: current_user.id).find_by(post_id: post.id) %>
                  <%= image_tag(check_avatar(current_user, 'thumb'), class:'like_avatar current_like_avatar') %>
                <% else%>
                  <%= image_tag(check_avatar(current_user, 'thumb'), class:'like_avatar current_like_avatar hidden') %>
                <% end %>
                <% if Like.where(post_id: post.id).any? %>
                  <% Like.where.not(user_id: current_user).where(post_id: post.id).order("RANDOM()").limit(3).each do |like|%>
                      <%= image_tag(check_avatar(like.user, 'thumb'), class:'like_avatar') %>
                  <% end %>
                <% end %>
              </span>
          <% end %>
          </span>
      <% else %>
        <div class = "btn btn-read noHover">
          <span class="not_liked"><%= image_tag('like.svg')%></span>
          <span style='color:black'><%= Like.where(post_id: post.id).count %></span>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/bookmarks.html.erb
<% provide(:page_title, 'Bookmarks') %>


<div class="row">
  <% Like.where(user_id: current_user.id).each do |like|%>
    <div class="col-md-6">
      <div class="well well-sm">
        <div class="row">
          <div class="col-xs-3 col-md-3 text-center", style='width: 150px; height: 130px;overflow:hidden'>
            <%= image_tag(Post.find(like.post_id).banner_image_url, class:"img-rounded img-responsive")%>
          </div>
          <div class="col-xs-9 col-md-9 section-box">
            <h2>
              <%= link_to Post.find(like.post_id).title, post_path(Post.find(like.post_id)), style:'color:black' %>
              <%= link_to " @#{User.find(like.user_id).username}", user_path(User.find(like.user_id).username), style: 'color: gray; font-weight: 300; font-size:20px;'%>
            </h2>
            <p><%= truncate(strip_tags(Post.find(like.post_id).body), length:130, separator:' ') %></p>
            <hr />
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<% provide(:page_title, "Edit '#{@post.title}'") %>
<% provide(:active_menu_item, 'blog') %>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<% provide(:page_title, 'All posts') %>
<% provide(:active_menu_item, 'blog') %>

<div class="row posts index">
  <%= render @posts %>
</div>
<div class = "apple_pagination">
  <%= will_paginate @posts %>
</div>

app/views/posts/new.html.erb
<% provide(:page_title, 'New') %>
<% provide(:active_menu_item, 'blog') %>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<% provide(:page_title, @post.title) %>
<% provide(:active_menu_item, 'blog') %>

<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
    <div class = 'post_topper' style = 'background-image: url(<%= @post.banner_image_url%>)'></div><br>
    <h2>
      <%= @post.title %>
      <%= link_to "@#{@post.user.username}", user_path(@post.user.username), style: "font-weight: 300; font-size: 22px; color: gray"%>
      <% if current_user && current_user.own?(@post) %> 
        <%= link_to image_tag('Edit.png'), edit_post_path(@post) %> 
      <% end %>
    </h2>
    <%= strip_tags(@post.body) %>
    <br>
    <div style = 'margin-top: 5px; font-style: italic;'>
        <%= @post.created_at.strftime("%d %b. %Y")%> <%= @post.created_at.strftime("%H:%M")%>
    </div>
    <hr style = 'background-color: black; height: 1px;'>
    <table class="table table-striped">
        <% @post.comments.where(approved: true).order(:created_at).map do |comment| %>
          <tr> 
            <td>
              <%= link_to "@#{comment.user.username}", user_path(comment.user.username), style: 'color: gray; font-weight: 500;' %> 
              said: <%=comment.text %> 
              <span style = 'color: gray'>(<%= comment.created_at.strftime("%d %b. %H:%M")%>)</span>
              <% if current_user == comment.user %>
              <%= link_to "Delete", post_comment_path(@post, comment),
                                                    method: :delete,
                                                    data: {confirm: "Are you sure?"},
                                                    style: 'float: right;', class: 'btn btn-sm btn-danger'%>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% if current_user %> <tr><td>
      <%= render 'comments/form', post: @post, comment: @comment %>
      </td></tr> <% end %>
    </table> 
  </div>   
</div>