config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/about' => 'pages#about', as: :about
  get '/contact' => 'pages#contact', as: :contact
  get '/chat', to: 'rooms#show'
  root to: 'posts#index'
  resources :posts do
    collection do
      get :bookmarks
    end
    member do
      get :like
    end
    resources :comments, param: :id, only: [:create, :destroy] do
      get :approve
    end
  end
  devise_for :users
  get '/:id' => 'users#show', as: :user

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<div class="login_background hidden"></div>
<div class="login_popup hidden">
  <div class="login-box">
    <div class="box-header"><h2>Log In</h2></div><br/>

    <%= form_for("user", :url => user_session_path) do |f| %>
        <div class="field">
          <label for="username">E-mail</label><br/>
          <%= f.email_field :email, autofocus: true %>
        </div>

        <div class="field">
          <label for="password">Password</label><br/>
          <%= f.password_field :password, autocomplete: "off" %>
        </div>

        <div class="actions">
          <%= f.submit "Log in", class:'button', style:"float:left;margin-left:60px;width:70px" %>
        </div>
    <% end %>

    <%= link_to new_user_registration_path do %>
          <button class="button" style='float:left;margin-left:40px;'>Sign Up</button>
    <% end %><br/><div style="clear: both;"></div>
    <%= link_to 'Forgot your password?', new_user_password_path, class:"small" %>
  </div>
</div>
<nav class="navbar navbar-light bg-faded navbar-static-top" xmlns:background-color="http://www.w3.org/1999/xhtml">
  <div class = 'container' style="padding-top: 0px">
    <a class='navbar-brand' href='/'>
      Senseless<span class='light'>blog</span>
    </a>
    <ul class="nav navbar-nav hidden-xs-down ", style="flex-direction: row; float:right">
      <li class="nav-item">
        <%= link_to 'Blog', root_path, class: "nav-link #{active_link(yield(:active_menu_item), 'blog')}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: "nav-link #{active_link(yield(:active_menu_item), 'about')}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact', contact_path, class: "nav-link #{active_link(yield(:active_menu_item), 'contact')}" %>
      </li>
      <% if user_signed_in? %>
          <li  class="nav-item dropdown">
            <%= image_tag(check_avatar(current_user,'thumb'), style:'width:30px; height:30px; margin: 5px 7px 0 0; border-radius: 15px; float:left;') %>
            <%= link_to current_user.username, "#", { class: "nav-link dropdown-toggle #{active_link(yield(:active_menu_item),
                                                      current_user.email )}", 'data-toggle' => "dropdown", style:'float:left' } %>
            <ul class="dropdown-menu custom_dropdown">
              <li class="dropdown-item">
                <%= link_to 'My profile', user_path(current_user.username) %>
              </li>
              <div class="dropdown-divider"></div>
              <li class="dropdown-item">
                <%= link_to 'New post', new_post_path %>
              </li>
              <li class="dropdown-item">
                <%= link_to 'Bookmarks', bookmarks_posts_path %>
              </li>
              <li class="dropdown-item">
                <%= link_to 'Live chat!', chat_path %>
              </li>
              <div class="dropdown-divider"></div>
              <li class="dropdown-item">
                <%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
              </li>
            </ul>
          </li>
      <% else %>
          <li  class="nav-item index-devise-block login_button"><%= link_to 'Login', '#', class: "nav-link #{active_link(yield(:active_menu_item), 'login')}" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lol | <%= yield (:page_title) %></title>
    <%= csrf_meta_tags %>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script>
    </script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
      <div class = 'container'>
      <div class="container <%= controller_name %> <%= action_name %>">
        <div id = 'flash'>
        <% flash.each do |key, value| %>
          <div class="<%= flash_class key %>"><%= value %></div>
        <% end %>
        </div>
    </div>
    <%= yield %>
    </div>
  </body>
</html>